---
- name: Create Cisco ACI Tenant
  hosts: LAB_APIC
  gather_facts: false

  tasks:
    - name: Ensure the Tenant exists on Cisco APIC LAB
      cisco.aci.aci_tenant:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ aci_validate_certs }}"
        tenant: "{{ tenant_name }}"
        state: "{{ tenant_state }}"
        output_level: "{{ aci_output_level }}"
      register: tenant_result

    - name: Show tenant result
      ansible.builtin.debug:
        var: tenant_result
